before_install:
  - sudo apt-get install libssl-dev
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libbz2-dev
  - sudo apt-get install libarchive-dev
  - sudo apt-get install libpcre3-dev
  - sudo apt-get install uuid-dev
  - sudo apt-get install poppler-utils
  - sudo apt-get install python-nose
  - sudo apt-get install yara
  - sudo apt-get install libyara-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc


# Build steps
script:
  - ./build.sh

