sudo: required
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install libssl-dev
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libbz2-dev
  - sudo apt-get install libarchive-dev
  - sudo apt-get install libpcre3-dev
  - sudo apt-get install uuid-dev
  - sudo apt-get install poppler-utils
  - sudo apt-get install python-nose

install:
  - wget https://github.com/VirusTotal/yara/archive/v3.7.0.tar.gz
  - tar -xzvf v3.7.0.tar.gz
  - cd yara-3.7.0
  - ./bootstrap.sh
  - ./configure
  - make
  - sudo make install
  - cd ../

# Build steps
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./build.sh ; fi

